CC=g++
CFLAGS=-I.

DEPS = CurrentConditionsDisplay.hpp DisplayElement.hpp \
	ForecastDisplay.hpp HeatIndexDisplay.hpp Observer.hpp \
	StatisticsDisplay.hpp Subject.hpp Utilities.hpp WeatherData.hpp
	
OBJ = WeatherStation.o CurrentConditionsDisplay.o \
	DisplayElement.o ForecastDisplay.o HeatIndexDisplay.o \
	Observer.o StatisticsDisplay.o Subject.o Utilities.o WeatherData.o
 
%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

WeatherStation: $(OBJ)
	g++ -o $@ $^ $(CFLAGS)

.PHONY : clean
clean:
	-rm -rf *.o